// <auto-generated />
using System;
using MediaCenterCMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaCenterCMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716145048_AddGalleryVideo")]
    partial class AddGalleryVideo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaCenterCMS.API.Models.ApprovalRequest", b =>
                {
                    b.Property<int>("ApprovalRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalRequestId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ApprovalRequestId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.GalleryImage", b =>
                {
                    b.Property<int>("GalleryImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GalleryImageId"));

                    b.Property<int?>("ApprovalRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VisibilityStatus")
                        .HasColumnType("integer");

                    b.HasKey("GalleryImageId");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MediaId");

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.GalleryVideo", b =>
                {
                    b.Property<int>("GalleryVideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GalleryVideoId"));

                    b.Property<int?>("ApprovalRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VisibilityStatus")
                        .HasColumnType("integer");

                    b.HasKey("GalleryVideoId");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MediaId");

                    b.ToTable("GalleryVideos");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("integer");

                    b.HasKey("MediaId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("NewsId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CurrentVersionId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("News");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.NewsVersion", b =>
                {
                    b.Property<int>("NewsVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NewsVersionId"));

                    b.Property<int?>("ApprovalRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CoverMediaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("NewsId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("NewsVersionId");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("CoverMediaId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsVersions");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Editor"
                        });
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.ApprovalRequest", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.User", "Requester")
                        .WithMany("RequestedApprovals")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaCenterCMS.API.Models.User", "Reviewer")
                        .WithMany("ReviewedApprovals")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Requester");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.AuditLog", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.GalleryImage", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.ApprovalRequest", "ApprovalRequest")
                        .WithMany()
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediaCenterCMS.API.Models.User", "Creator")
                        .WithMany("GalleryImages")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaCenterCMS.API.Models.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("Creator");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.GalleryVideo", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.ApprovalRequest", "ApprovalRequest")
                        .WithMany()
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediaCenterCMS.API.Models.User", "Creator")
                        .WithMany("GalleryVideos")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaCenterCMS.API.Models.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("Creator");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.Media", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.User", "Uploader")
                        .WithMany("UploadedMedia")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.News", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.User", "Creator")
                        .WithMany("CreatedNews")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaCenterCMS.API.Models.NewsVersion", "CurrentVersion")
                        .WithOne()
                        .HasForeignKey("MediaCenterCMS.API.Models.News", "CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediaCenterCMS.API.Models.User", "Updater")
                        .WithMany("UpdatedNews")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("CurrentVersion");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.NewsVersion", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.ApprovalRequest", "ApprovalRequest")
                        .WithMany()
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediaCenterCMS.API.Models.Media", "CoverMedia")
                        .WithMany()
                        .HasForeignKey("CoverMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaCenterCMS.API.Models.User", "Creator")
                        .WithMany("CreatedVersions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaCenterCMS.API.Models.News", "News")
                        .WithMany("Versions")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("CoverMedia");

                    b.Navigation("Creator");

                    b.Navigation("News");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.User", b =>
                {
                    b.HasOne("MediaCenterCMS.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.News", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MediaCenterCMS.API.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedNews");

                    b.Navigation("CreatedVersions");

                    b.Navigation("GalleryImages");

                    b.Navigation("GalleryVideos");

                    b.Navigation("RequestedApprovals");

                    b.Navigation("ReviewedApprovals");

                    b.Navigation("UpdatedNews");

                    b.Navigation("UploadedMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
